server:
  port: 8080

spring:
  application:
    name: gateway-service
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    gateway:

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        - id: user-service
          uri: lb://user
          predicates:
            - Path=/api/v1/users/**

        - id: booking-service
          uri: lb://booking
          predicates:
            - Path=/api/v1/bookings/**

        - id: schedule-service
          uri: lb://schedule
          predicates:
            - Path=/api/v1/schedules/**

        - id: movie-service
          uri: lb://movie
          predicates:
            - Path=/api/v1/movies/**

        - id: studio-service
          uri: lb://studio
          predicates:
            - Path=/api/v1/studios/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"