server:
  port: 8080

spring:
  application:
    name: gateway-service
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    gateway:

      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**

        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: JwtAuthenticationFilter

        - id: booking-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/bookings/**
          filters:
            - name: JwtAuthenticationFilter

        - id: schedule-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/schedules/**
          filters:
            - name: JwtAuthenticationFilter

        - id: movie-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/movies/**
          filters:
            - name: JwtAuthenticationFilter

        - id: studio-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/studios/**
          filters:
            - name: JwtAuthenticationFilter

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG